language: node_js
node_js:
  - "node"
  - "6"
install:
  npm install -G cross-env
  npm install -G webpack

script:
- npm install
- npm run build

branches:
  only:
  - master
  - development

skip_cleanup: true