language: node_js
node_js:
  - "node"
  - "6"

script:
- npm install
- npm install -G cross-env
- npm run build

branches:
  only:
  - master
  - development

skip_cleanup: true
env:
 - NODE_ENV=production