name: 'Find signed commits'

on:
  pull_request_target:

jobs:
  check-sign-off:
    if: startsWith(github.head_ref, 'releases/v') == false
    name: Write comment if unsigned commits found
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest

    steps:
      - uses: live627/check-pr-signoff-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
